image: python:3.12

stages:
  - test

before_script:
  - python --version
  - pip install -r requirements.txt

selenium_test:
  stage: test
  script:
    - mkdir -p reports
    - pytest tests --html=reports/report.html --self-contained-html
  artifacts:
    when: always
    paths:
      - reports/